// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/15/2025, 5:32:36 PM
const configMerger = require("/Users/jeongyunl/Documents/GitHub/juso-chatbot-v2/frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/jeongyunl/Documents/GitHub/juso-chatbot-v2/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jeongyunl/Documents/GitHub/juso-chatbot-v2/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jeongyunl/Documents/GitHub/juso-chatbot-v2/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jeongyunl/Documents/GitHub/juso-chatbot-v2/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jeongyunl/Documents/GitHub/juso-chatbot-v2/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jeongyunl/Documents/GitHub/juso-chatbot-v2/frontend/plugins/**/*.{js,ts,mjs}","/Users/jeongyunl/Documents/GitHub/juso-chatbot-v2/frontend/composables/**/*.{js,ts,mjs}","/Users/jeongyunl/Documents/GitHub/juso-chatbot-v2/frontend/utils/**/*.{js,ts,mjs}","/Users/jeongyunl/Documents/GitHub/juso-chatbot-v2/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/jeongyunl/Documents/GitHub/juso-chatbot-v2/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/jeongyunl/Documents/GitHub/juso-chatbot-v2/frontend/app.config.{js,ts,mjs}"] }));

module.exports = config
